import cv2
import numpy as np
image = cv2.imread('damaged_car.jpg')
resized_image = cv2.resize(image, (512, 512))
gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
blurred_image = cv2.GaussianBlur(gray_image, (5, 5), 0)
edges = cv2.Canny(blurred_image, threshold1=50, threshold2=150)
kernel = np.ones((5, 5), np.uint8)
dilated_edges = cv2.dilate(edges, kernel, iterations=1)
closed_edges = cv2.morphologyEx(dilated_edges, cv2.MORPH_CLOSE, kernel)
contours, _ = cv2.findContours(closed_edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour_image = resized_image.copy()
cv2.drawContours(contour_image, contours, -1, (0, 255, 0), 2)
cv2.imshow('Detected Contours', contour_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
